- name: Include variables specific for RHEL 8
  include_vars:
    file: RedHat-8.yml
  when:
  - ansible_os_family == "RedHat"
  - ansible_distribution_major_version == "8"

- name: Include variables specific for RHEL 7
  include_vars:
    file: RedHat-7.yml
  when:
  - ansible_os_family == "RedHat"
  - ansible_distribution_major_version == "7"

- import_tasks: pgsql_version.yml
  tags:
    - always

- include_tasks: "{{ pgsqlrep_role }}.yml"
  when: pgsqlrep_role != 'skip'
