- name: Include variables specific for RHEL 8
  include_vars:
    file: RedHat-8.yml
  when:
  - ansible_os_family == "RedHat"
  - ansible_distribution_major_version == "8"

- name: Include variables specific for RHEL 7
  include_vars:
    file: RedHat-7.yml
  when:
  - ansible_os_family == "RedHat"
  - ansible_distribution_major_version == "7"

- name: Get PGSQL version
  command: "{{ pgsql_version_command }}"
  changed_when: no
  check_mode: no
  register: pgsql_version_check
  tags:
    - always

- name: Set PGSQL version
  set_fact:
#    pgsql_version: "{{ pgsql_version_check['stdout'].split()[-1][:3] }}"
    pgsql_version: "{{ pgsql_version_check['stdout'].split()[-1][:2] }}"
  tags:
    - always
