---


- name: determine if vault params in use
  set_fact:
#    tower_vault_params: "--vault-password-file={{playbook_dir}}/.vault-pass"
    tower_vault_params: "--vault-password-file={{ tower_vault_file }}"
  when: tower_vault_file is defined

- name: run tower installer for version {{ tower_version }}
#  command: "./setup.sh -i {{ tower_install_inventory }} {{ tower_install_extra_vars }} -- {{ tower_vault_params }} "
  shell: "scl enable rh-python36 -- ./setup.sh -i {{ tower_install_inventory }} {{ tower_install_extra_vars }} -- {{ tower_vault_params }} "
  args:
    chdir: "{{ tower_installer_current }}"
  environment:
    ANSIBLE_BECOME_METHOD: sudo
    ANSIBLE_BECOME: True
  register: tower_install_status
  ignore_errors: yes
  when: not (tower_install_skip | bool)

- name: fail with message
  fail:
    msg: "Tower installation failed.  Please check {{ tower_installer_current }}/setup.log"
  when: "'skipped' not in tower_install_status and tower_install_status.failed"
